spring:
   datasource:
     url: jdbc:mysql://localhost:3306/anonymous_guestbook?serverTimezone=Asia/Seoul
     username: root
     password: 1234
   jpa:
     hibernate:
       ddl-auto: update
     show-sql: true
     properties:
       hibernate:
         format_sql: true


server:
  port: 8888